name: Update OpenWrt Packages
on: 
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
  - cron: 0 */12 * * *

env:
  TZ: Asia/Shanghai

jobs:
  Update_OpenWrt_Packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup Python 3.9.x
        uses: actions/setup-python@main
        with:
          python-version: '3.9.x'

      - name: Install Dependencies
        run: |
          sudo timedatectl set-timezone "$TZ"
          python -m pip install --upgrade pip
          pip install -U GitPython

      - name: Update OpenWrt Packages
        id: update
        run: |
          python packages.py
          rm -rf __pycache__
          echo "message=$(date)" >> $GITHUB_OUTPUT

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ steps.update.outputs.message }}
          
      - name: Build APK for AN7581
        run: |
          BASE_URL="https://downloads.openwrt.org"
          FILE_NAME=$(curl -s "$BASE_URL" | grep -oE "openwrt-sdk-airoha-an7581_[^\"'>]+\.tar\.xz" | head -n 1)
          
          if [ -z "$FILE_NAME" ]; then
            echo "错误：无法在 $BASE_URL 找到 SDK 文件名！"
            exit 1
          fi
          
          FULL_URL="${BASE_URL}${FILE_NAME}"
          echo "正在从此地址下载 SDK: $FULL_URL"
          
          wget -q "$FULL_URL" -O sdk_archive.tar.xz
          mkdir -p sdk
          tar -xJf sdk_archive.tar.xz -C sdk --strip-components=1
          
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
          cp -r ../luci-app-gecoosac package/ || echo "警告：未找到源码文件夹"
          
          make defconfig
          make package/luci-app-gecoosac/compile V=s || true

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gecoosac-apk-an7581
          path: sdk/bin/targets/airoha/an7581/packages/*.apk


      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 2
